# Generated by Django 4.2.14 on 2024-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
