# Generated by Django 4.2.14 on 2024-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_article_id_postcomment_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
